/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tarent.coap.intro.client;

import org.eclipse.californium.core.CoapClient;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        CoapClient client = new CoapClient();

        //access  HelloWorldResource
    }
}
