/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tarent.coap.intro.client;

import org.eclipse.californium.core.CoapClient;
import org.eclipse.californium.core.CoapResponse;
import org.eclipse.californium.core.Utils;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        CoapClient client = new CoapClient("coap://localhost/Hello");
        try {
            CoapResponse response = client.get();
            
            if (response!=null) {
                System.out.println(Utils.prettyPrint(response));
                
            } else {
                
                System.out.println("Request failed");
                
            }
        } catch(Exception cex) {
            cex.printStackTrace();
        }
    }
}
