/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tarent.coap.intro.client;

import org.eclipse.californium.core.CoapClient;
import org.eclipse.californium.core.CoapResponse;

import org.eclipse.californium.core.Utils;
import org.eclipse.californium.core.coap.MediaTypeRegistry;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        CoapClient client = new CoapClient("coap://localhost/Hello");
        try {
            CoapResponse response = client.get();
            
            if (response!=null) {
            
                System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
				System.out.println(Utils.prettyPrint(response));
                
            } else {
                
                System.out.println("Request failed");
                
            }
        } catch(Exception cex) {
            cex.printStackTrace();
        }

        client = new CoapClient("coap://localhost/subpath/Another");
        try {
            CoapResponse response = client.get();
            
            if (response!=null) {
                System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
				System.out.println(Utils.prettyPrint(response));
            } else {
                
                System.out.println("Request failed");
                
            }
        } catch(Exception cex) {
            cex.printStackTrace();
        }

        client = new CoapClient("coap://localhost/time");
        try {
            CoapResponse response = client.get();
            
            if (response!=null) {
                System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
				System.out.println(Utils.prettyPrint(response));
            } else {
                
                System.out.println("Request failed");
                
            }
        } catch(Exception cex) {
            cex.printStackTrace();
        }

        client = new CoapClient("coap://localhost/removeme!");
        try {
            CoapResponse response = client.delete();
            
            if (response!=null) {
                System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
				System.out.println(Utils.prettyPrint(response));
            } else {
                
                System.out.println("Request failed");
                
            }
        } catch(Exception cex) {
            cex.printStackTrace();
        }
        client = new CoapClient("coap://localhost/writeme!");
        try {
            CoapResponse response = client.get();
            
            if (response!=null) {
                System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
				System.out.println(Utils.prettyPrint(response));
            } else {
                
                System.out.println("Request failed");
                
            }

            response = client.put("test", MediaTypeRegistry.TEXT_PLAIN);

            if (response!=null) {
                System.out.println(System.lineSeparator() + "ADVANCED" + System.lineSeparator());
					// access advanced API with access to more details through
					// .advanced()
				System.out.println(Utils.prettyPrint(response));
            } else {
                
                System.out.println("Request failed");
                
            }

        } catch(Exception cex) {
            cex.printStackTrace();
        }
    }
}
