/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tarent.coap.intro.server;

import org.eclipse.californium.core.CoapServer;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // binds on UDP port 5683
        CoapServer server = new CoapServer();

        //add helloWorld Resource
    }
}
